// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2Store.ShopUI.Models;

#nullable disable

namespace Project2Store.ShopUI.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Project2Store.ShopUI.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Mobile",
                            Description = "Ram 8 Hard 254",
                            Name = "Samsung A54",
                            Price = 12000000
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Mobile",
                            Description = "Ram 4 Hard 254",
                            Name = "Samsung A52",
                            Price = 10000000
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Mobile",
                            Description = "Ram 2 Hard 254",
                            Name = "Samsung A50",
                            Price = 8000000
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Mobile",
                            Description = "Ram 2 Hard 54",
                            Name = "Samsung A32",
                            Price = 5000000
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Laptop",
                            Description = "ram 18 254gb",
                            Name = "Asus vivabook515",
                            Price = 40000000
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Laptop",
                            Description = "ram 32 254gb",
                            Name = "Asus vivabook515xf",
                            Price = 45000000
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Laptop",
                            Description = "ram 32 128gb",
                            Name = "Asus vivabook400xf",
                            Price = 35000000
                        },
                        new
                        {
                            Id = 8L,
                            Category = "PC",
                            Description = "1056 * 1000 HZ",
                            Name = "Monitor Apple",
                            Price = 10000000
                        },
                        new
                        {
                            Id = 9L,
                            Category = "PC",
                            Description = "5056 * 3000 HZ",
                            Name = "Monitor Dc",
                            Price = 20000000
                        },
                        new
                        {
                            Id = 10L,
                            Category = "PC",
                            Description = "2056 * 3000 HZ",
                            Name = "Monitor Samsung",
                            Price = 15000000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
